# Use a Node.js base image
FROM node:16

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY support-system/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY support-system/ .

# Expose the port the Support system will run on
EXPOSE 3003

# Command to run the application
CMD ["node", "app.js"]
