# Use a Node.js base image
FROM node:16

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY inventory-system/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY inventory-system/ .

# Expose the port the Inventory system will run on
EXPOSE 3002

# Command to run the application
CMD ["node", "app.js"]
